#!/usr/bin/env bash

name='house-of-tartan'
ident='house_of_tartan'

/usr/bin/env python cli.py ${name} $*

mkdir -p data/${name}
cp storage/${ident}/data.csv data/${name}
cp storage/${ident}/datapackage.json data/${name}
