#!/usr/bin/env bash

name='house-of-tartan'
ident='house_of_tartan'

if mkdir -p storage/${ident}
then
  cp data/${name}/datapackage.json storage/${ident}/datapackage.json 2>/dev/null
  /usr/bin/env python cli.py ${name} $*

  mkdir -p data/${name}
  cp storage/${ident}/data.csv data/${name} 2>/dev/null
  cp storage/${ident}/datapackage.json data/${name} 2>/dev/null

  exit
fi

echo "Something went wrong"
