#!/usr/bin/env bash

name='weddslist'
ident='weddslist'

if mkdir -p storage/${ident}
then
  cp data/${name}/datapackage.json storage/${ident}/datapackage.json 2>/dev/null
  __CLI_TOOL_WRAPPER=$0 /usr/bin/env python cli.py ${name} $*

  mkdir -p data/${name}
  cp storage/${ident}/data.csv data/${name} 2>/dev/null
  cp storage/${ident}/datapackage.json data/${name} 2>/dev/null

  exit
fi

echo "Something went wrong"
